### PR TITLE
[docs] clarify you can use index sets when setting the start value

### LINKED ISSUE #3147: [docs] clarify you can use index sets when setting the start value
Question from SO: https://stackoverflow.com/questions/74732967/how-does-one-elegantly-initialize-start-values-or-parameter-values-when-creating/74735001

### PR DESCRIPTION
**Pull request by odow**
Closes #3147

### CODE REVIEW

**Comment by odow** [comment]
@ajcost I saw your comment too late 😆  Was this sufficient?

From your SO post:

> apologies as I am new to the language and tried all resources but cannot find a solution to this problem

Hi! Feedback on our documentation from newcomers is _super_ helpful. If you get stuck at any point, please open a PR or leave a comment here: https://github.com/jump-dev/JuMP.jl/issues/2348. 

You can make a PR to the docs by clicking the pencil icon in the top-right corner of any page of the documentation:

image

**Comment by ajcost** [comment]
@odow no worries, yeah super helfpul only other suggestion is to maybe have the same doc level for @NLparameter as you do for @variable with the examples etc. but other than that it was super understandable. 

Great project!

**Comment by odow** [comment]
Do you mean here https://jump.dev/JuMP.jl/stable/reference/nlp/#JuMP.@NLparameter?

Or here https://jump.dev/JuMP.jl/stable/manual/nlp/#Create-a-nonlinear-parameter?

**Comment by ajcost** [comment]
yep nevermind that's what i was thinking of

**Pull request merged**
