### PR TITLE
Doc cleanup workflow

### LINKED ISSUE #2721: gh-pages branch can get big with `push_preview=true`
Hello, 

I just came across this in the Documenter docs https://juliadocs.github.io/Documenter.jl/stable/man/hosting/#gh-pages-Branch

Enabling `push_preview=true` is very useful but can create a lot of unnecessary files in the gh-pages branch. They have published a github workflow to remove stale documentation previews. 

```
name: Doc Preview Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  doc-preview-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout gh-pages branch
        uses: actions/checkout@v2
        with:
          ref: gh-pages
      - name: Delete preview and history + push changes
        run: |
            if [ -d "previews/PR$PRNUM" ]; then
              git config user.name "Documenter.jl"
              git config user.email "documenter@juliadocs.github.io"
              git rm -rf "previews/PR$PRNUM"
              git commit -m "delete preview"
              git branch gh-pages-new $(echo "delete history" | git commit-tree HEAD^{tree})
              git push --force origin gh-pages-new:gh-pages
            fi
        env:
            PRNUM: ${{ github.event.number }}
```

Is it worth it to add this action to the repository?

### PR DESCRIPTION
**Pull request by guilhermebodin**
This closes #2721

### CODE REVIEW

**Review by odow — APPROVED** [review]
So this just cleans up new PRs when they are closed? I guess we need to manually clean up the existing ones?

There are a heeeeeap of existing ones: 
https://github.com/jump-dev/JuMP.jl/tree/gh-pages/previews

**Comment by guilhermebodin** [comment]
I am testing on StateSpaceModels.jl but yes I think it does not clean the old ones.

**Comment by odow** [comment]
Wow yeah, the existing files are huge! Uncompressed they were 7.8 MB per pull request being added to the `.git`. This is great to have going forward. I'll sort the existing folders.

**Comment by odow** [comment]
After https://github.com/jump-dev/JuMP.jl/commit/e5eacca75241e4f2bdff1d983426514cb0458b32, we're at
```
(base) oscar@Oscars-MBP JuMP %  du -h -d 1 .    
852K	./v0.21.3
868K	./v0.21.5
520K	./v0.19-beta2
668K	./v0.20.0
676K	./v0.20.1
3.5M	./0.14
2.4M	./0.13
1.9M	./0.12
3.5M	./0.15
372K	./v0.19-alpha
612K	./v0.19.2
5.0M	./v0.21.9
816K	./v0.21.0
5.1M	./v0.21.7
484K	./v0.19-beta
2.5M	./v0.21.6
5.2M	./v0.21.10
816K	./v0.21.1
4.9M	./v0.21.8
7.8M	./dev
 63M	./previews
118M	./.git
  0B	./.vscode
372K	./release-0.19
616K	./v0.19.0
3.6M	./0.17
612K	./v0.19.1
3.5M	./0.16
3.7M	./0.18
241M	.
```

**Pull request merged**
