### PR TITLE
JuliaFormatter: separate_kwargs_with_semicolon

### PR DESCRIPTION
**Pull request by odow**
Part of #2990 

I think this is a reasonable change, because it can only ever reduce confusion.

### CODE REVIEW

**Comment by mlubin** [comment]
It looks a bit uglier to me, but I guess the disambiguity argument with `sum(i for i in 1:0; init = 0)` is more important.

**Comment by odow** [comment]
The original motivation was https://discourse.julialang.org/t/keyword-behaves-differently-using-or/78233. @ccoffrin and I hit it in some NLP/PowerModels stuff.

**Comment by odow** [comment]
Hmm. I guess I didn't try:
```Julia
julia> using JuliaFormatter

julia> format_text("sum(i for i in 1:0, init = 0)"; separate_kwargs_with_semicolon = true)
"sum(i for i = 1:0, init in 0)"

julia> format_text("sum(i for i in [], init = 0)"; separate_kwargs_with_semicolon = true)
"sum(i for i in [], init in 0)"
```
So it won't fix the `sum` problem, but it will make clear that something is wrong.

**Comment by odow** [comment]
Okay for now. I'll look into whether we can exclude `;` if they are in a function call with kwargs only.

**Pull request merged**
