### PR TITLE
Add Convex.jl to solver list

### PR DESCRIPTION
**Pull request by blegat**
The MOI wrapper was added in Convex.jl v0.16

### CODE REVIEW

**Comment by mlubin** [comment]
This needs more caveats, like those mentioned at https://github.com/jump-dev/Convex.jl?tab=readme-ov-file#using-with-jump.

**Comment by mlubin** [comment]
I'm also having trouble thinking of which important use cases of DCP are covered without vector input functions like `norm`. Is it really worth advertising?

**Comment by odow** [comment]
Agree. I'm still treating this as somewhat experimental.

**Comment by blegat** [comment]
I agree there is maybe not point advertising this yet, let's close this

**Pull request closed without merging**
