### PR TITLE
Add plotting to tutorials

### PR DESCRIPTION
**Pull request by odow**
Part of #2483

We should check how long CI takes before merging.

### CODE REVIEW

**Comment by odow** [comment]
ooof. CI time went from 12 minutes to 18.

It does print the plot: https://jump.dev/JuMP.jl/previews/PR2497/tutorials/Nonlinear%20programs/rocket_control/#Display-results
image
but it looks like I need to work on the margins.

**Comment by ferrolho** [comment]
Hopefully, that time should come down with the upgrade to Julia 1.6.

**Comment by odow** [comment]
Yes. Once 1.6 is released, I think it is reasonable to move the doc build from 1.0 to 1.6. That will allow us to use the jll builds for GLPK, Ipopt, and SCS as well, which should reduce the build/install times.

This is also only a price we pay once, so adding better plots to the rest of the tutorials should be cheap.

**Comment by odow** [comment]
There you go. Please rebase your tutorial, or wait for #2498 if you want to re-add the `const` terms.

**Comment by ferrolho** [comment]
I'll wait for #2498 to be merged. Thanks for this!

**Comment by odow** [comment]
It's merged.

**Pull request merged**
