### PR TITLE
Small tweaks to Tolerances tutorial

### PR DESCRIPTION
**Pull request by jd-foster**
Nice write-up Oscar.

### CODE REVIEW

**Review by odow — APPROVED** [review]
I still need to find out why vale thinks `eample` is a word. It's happened before

**Comment by odow** [comment]
Yeah I liked it. I don't really recall seeing such an explicit write up in other places. The Gurobi docs have it in pieces, but they're often just throw-away sentences like "this could happen". Seeing it in code from HiGHS is something else.

**Comment by odow** [comment]
I like the example at the end where HiGHS says it is infeasible. But then if you provide a starting point it's like "hey that is actually feasible!"

**Comment by jd-foster** [comment]
> I still need to find out why vale thinks eample is a word. It's happened before

Random thought: because it contains `ampl`??

**Pull request merged**
