### PR TITLE
Fixes for arithmetic with complex quadratic

### PR DESCRIPTION
**Pull request by blegat**
@ccoffrin You can use the branch https://github.com/jump-dev/JuMP.jl/tree/bl/complex_full for testing. It includes the changes from:

* https://github.com/jump-dev/JuMP.jl/pull/2905,
* https://github.com/jump-dev/JuMP.jl/pull/2904 and
* this PR (https://github.com/jump-dev/JuMP.jl/pull/2903)

### CODE REVIEW

**Review by odow — APPROVED** [review]

**Comment by ccoffrin** [comment]
@blegat thanks for this!  Here is another test.

Formulation seems to be working, but hard to know for sure because I can't yet solve the model.  When I try to run the model with Ipopt I get, `ERROR: LoadError: Constraints of type MathOptInterface.ScalarAffineFunction{ComplexF64}-in-MathOptInterface.EqualTo{ComplexF64} are not supported by the solver.`

I did not manage to get this variable syntax working, https://github.com/jump-dev/ComplexOptInterface.jl/issues/13, but building my own complex Dict provided an easy work around (`V = Dict(i => vr[i] + vi[i]*im for i in keys(ref[:bus]))`).

I did notice this in the arithmetic engine,
```
T = V_fr*conj(V_fr)
println(real(T)) -> vr[3]² + 0 vi[3]*vr[3] + vi[3]²
println(imag(T)) -> 0 vr[3]² + 0 vi[3]*vr[3] + 0 vi[3]²

W = V_fr*conj(V_to)
println(real(W)) -> vr[3]*vr[4] + 0 vr[3]*vi[4] + 0 vi[3]*vr[4] + vi[3]*vi[4]
println(imag(W)) -> 0 vr[3]*vr[4] - vr[3]*vi[4] + vi[3]*vr[4] + 0 vi[3]*vi[4]
```
And wondered if these `0` terms could yield an issue inside of some solver or if automatic simplification may be possible.

**Comment by odow** [comment]
> Formulation seems to be working, but hard to know for sure because I can't yet solve the model.

Did you run
```julia
COI.add_all_bridges(model)
```

Do you have a reproducible example?

**Comment by ccoffrin** [comment]
I did not try `COI.add_all_bridges(model)`, you can review the working example on the complex branch of this repo, https://github.com/ccoffrin/rosetta-opf/blob/complex/jump-complex.jl

**Comment by blegat** [comment]
I think https://github.com/ccoffrin/rosetta-opf/ is a private repo, I can't access it.
`ERROR: LoadError: Constraints of type MathOptInterface.ScalarAffineFunction{ComplexF64}-in-MathOptInterface.EqualTo{ComplexF64} are not supported by the solver` is expected if you don't call `ComplexOptInterface.add_all_bridges(model)` as mentioned by @odow above.

> And wondered if these `0` terms could yield an issue inside of some solver or if automatic simplification may be possible.

They are removed when the constraint gets added to the MOI backend. As a matter of fact, they don't appear when printing the constraint since it shows the function added to the MOI backend. By the way, this is not related to convex expressions as shown below:
```julia
julia> a = x + x^2 - x
x² + 0 x

julia> @constraint(model, a == 1)
x² = 1.0
```
Anyway, solver wrappers are robust against non-canonical functions and they will eliminate zeros as well.

**Comment by odow** [comment]
> I think https://github.com/ccoffrin/rosetta-opf/ is a private repo

Yeah it's something Carleton and I have been working on.

**Comment by ccoffrin** [comment]
Following the example @odow provided I can confirm that everything is working for Complex QCQP AC-OPF with `ComplexOptInterface v0.1.0` and `JuMP.jl.git#bl/complex_full`. Ipopt solve trace is identical to the one I get from a hand written version just using real valued variables and constraints.

**Comment by ccoffrin** [comment]
It's pretty cool, you can basically write this math model natively in JuMP, https://lanl-ansi.github.io/PowerModels.jl/stable/math-model/#AC-Optimal-Power-Flow

**Pull request merged**
