### PR TITLE
Embed the stable MathOptInterface docs into JuMP.

### PR DESCRIPTION
**Pull request by odow**
Not sure if we should do this (ever, or just yet), but I thought I would see what it looks like and get some feedback.

I'll post the preview link once the build finishes.

https://jump.dev/JuMP.jl/previews/PR2522/moi/

The idea is to make it easier for the JuMP docs to link to the MOI documentation,
and provide a single, unified set of documentation for JuMP/MOI. This should allow us to de-duplicate things like "What is a caching optimizer", and it provides a way for JuMP users to see things like "What sets are supported by MOI"

Things are controlled by pinning the MOI version in `docs/Project.toml`, so whenever we release MOI, we should update the pin and tag a new JuMP release to push the new docs.

### CODE REVIEW

**Comment by odow** [comment]
Before merging this, we should update to the revised MOI docs (v0.9.21) and rewrite the introduction page to make clear that this is a copy of the MOI documentation.

**Comment by odow** [comment]
So thoughts on this?

**Comment by joaquimg** [comment]
I like this!
Brainstorming: should we add the warning explaining it is a copy of MOI docs in all pages? (I don't know, I liked to see it in the 1st page).

**Comment by odow** [comment]
How's this:
image

**Review by blegat — APPROVED** [review]

**Comment by odow** [comment]
Done in #2695

**Pull request closed without merging**
