### PR TITLE
Add <--> syntax support for reified constraints

### PR DESCRIPTION
**Pull request by odow**
x-ref #2227

So far, MiniZinc.jl is the only solver supporting `MOI.Reified`, but we've discussed adding this syntax in #2227.

### CODE REVIEW

**Comment by odow** [comment]
Hmm. This passes tests locally:
```raw
(base) oscar@Oscars-MBP JuMP % julia --project=. test/runtests.jl test_reified.jl
[ Info: Loading test_reified.jl
Test Summary:         | Pass  Total
test_reified.jl:test_ |    8      8
Test Summary:                   |
test_reified.jl:test_extension_ | No tests
```

**Comment by blegat** [comment]
I like the idea of `{ ... }`, it's consistent with indicator constraints. How standard is `:=` though ? Could we make `<=>` and `⇔` work as well ?

**Comment by odow** [comment]
We can't make `<=>` work because it doesn't parse:
```julia
julia> :(z <=> {a in b})
ERROR: syntax: space before "{" not allowed in "> {" at REPL[1]:1
Stacktrace:
 [1] top-level scope
   @ none:1
```

`\iff` works, but that's not very helpful without an ascii fallback.
```julia
julia> :(z ⟺ {a in b})
:(z ⟺ {a in b})
```

**Comment by odow** [comment]
Ahh. But this is available:
```Julia
julia> :(a <--> b)
:(a <--> b)

julia> dump(:(a <--> b))
Expr
  head: Symbol call
  args: Array{Any}((3,))
    1: Symbol <-->
    2: Symbol a
    3: Symbol b
```

**Comment by chriscoey** [comment]
`<-->` looks OK. Out of curiosity, is there a list of available Julia operator symbols somewhere? Where did you find `<-->`?

**Comment by odow** [comment]
This isn't a great answer, but the list of symbols is in the parser:

https://github.com/JuliaLang/julia/blob/9c563ad6a4b5568e07d88776c42dd5c47fabc45b/src/julia-parser.scm#L13

I originally found it via trial-and-error...

**Comment by chriscoey** [comment]
oo, so many arrows. would be nice if the implication constraint and reified constraint arrows are consistent e.g. `-->` and `<-->`

**Comment by odow** [comment]
> would be nice if the implication constraint and reified constraint arrows are consistent e.g. --> and <-->

Yes, we could add `-->` support.

**Comment by mlubin** [comment]
Very cool, I didn't expect this would be so easy!

**Comment by odow** [comment]
> Very cool, I didn't expect this would be so easy!

Yes! https://github.com/jump-dev/JuMP.jl/issues/2227 has spurred quite a few changes that made this easy.

**Review by blegat — APPROVED** [review]

**Pull request merged**
