### PR TITLE
Re-enable SpecialFunctions in NLP

### LINKED ISSUE #1803: erf not defined
I'm solving a non-linear optimization problem with JuMP, there is an erf() called in my objective function. My code throws an error saying that the erf() function is not defined.

Since erf() has been moved from Base to SpecialFunctions I have called Pkg.update(), loaded the SpecialFunctions package, and swtiched among different solvers (NLopt, Itopt). Unfortunately none of them works. It occurs to me a bug in JuMP.

Here follows the environment and the minimized code which I tested.

```julia
julia> versioninfo()
Julia Version 1.0.3
Commit 099e826241 (2018-12-18 01:34 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i7 CPU         860  @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, nehalem)
Environment:
  JULIA_EDITOR = "C:\Users\binha\AppData\Local\atom\app-1.34.0\atom.exe" -a
  JULIA_NUM_THREADS = 4

julia> Pkg.installed()
Dict{String,Union{Nothing, VersionNumber}} with 25 entries:
"Statistics"          => nothing
"GR"                  => v"0.37.0"
"Distributions"       => v"0.16.4"
"Random"              => nothing
"Atom"                => v"0.7.14"
"UUIDs"               => nothing
"FastGaussQuadrature" => v"0.3.2"
"JuMP"                => v"0.18.5"
"Juno"                => v"0.5.4"
"LinearAlgebra"       => nothing
"Ipopt"               => v"0.5.1"
"NLopt"               => v"0.5.1"
"PyCall"              => v"1.18.5"
"LaTeXStrings"        => v"1.0.3"
"SymPy"               => v"0.8.3"
"StatsBase"           => v"0.27.0"
"Plots"               => v"0.22.5"
"PyPlot"              => v"2.7.0"
"ProgressMeter"       => v"0.9.0"
"QuadGK"              => v"2.0.3"
"NLsolve"             => v"3.0.1"
"SpecialFunctions"    => v"0.7.2"
"ECOS"                => v"0.9.4"
"PoissonRandom"       => v"0.4.0"
"PlotlyJS"            => v"0.12.2"

julia> using JuMP
julia> using NLopt
julia> using SpecialFunctions

julia> erf(1)
0.8427007929497149

julia> m=Model(solver=NLoptSolver(algorithm=:LD_MMA))
Feasibility problem with:
 * 0 linear constraints
 * 0 variables
Solver is NLopt

julia> @variable(m,x,start=0.0)
x

julia> @NLobjective(m,Min,erf(x))
JuMP.NonlinearExprData(ReverseDiffSparse.NodeData[NodeData(CALLUNIVAR, 53, -1), NodeData(VARIABLE, 1, 1)], Float64[])

julia> solve(m)
ERROR: UndefVarError: erf not defined
Stacktrace:
 [1] #forward_eval#7(::ReverseDiffSparse.UserOperatorRegistry, ::Function, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{ReverseDiffSparse.NodeData,1}, ::SparseArrays.SparseMatrixCSC{Bool,Int64}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}) at C:\Users\binha\.julia\packages\ReverseDiffSparse\gvK2V\src\forward.jl:380
 [2] #forward_eval at .\none:0 [inlined]
 [3] forward_eval_all(::JuMP.NLPEvaluator, ::Array{Float64,1}) at C:\Users\binha\.julia\packages\JuMP\PbnIJ\src\nlp.jl:445
 [4] eval_grad_f(::JuMP.NLPEvaluator, ::Array{Float64,1}, ::Array{Float64,1}) at C:\Users\binha\.julia\packages\JuMP\PbnIJ\src\nlp.jl:496
 [5] initialize(::JuMP.NLPEvaluator, ::Array{Symbol,1}) at C:\Users\binha\.julia\packages\JuMP\PbnIJ\src\nlp.jl:403
 [6] loadproblem!(::NLopt.NLoptMathProgModel, ::Int64, ::Int64, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Symbol, ::JuMP.NLPEvaluator) at C:\Users\binha\.julia\packages\NLopt\eqN9a\src\NLoptSolverInterface.jl:117
 [7] _buildInternalModel_nlp(::Model, ::JuMP.ProblemTraits) at C:\Users\binha\.julia\packages\JuMP\PbnIJ\src\nlp.jl:1244
 [8] #build#123(::Bool, ::Bool, ::JuMP.ProblemTraits, ::Function, ::Model) at C:\Users\binha\.julia\packages\JuMP\PbnIJ\src\solvers.jl:304
 [9] #build at .\none:0 [inlined]
 [10] #solve#120(::Bool, ::Bool, ::Bool, ::Base.Iterators.Pairs{Union{},Union{},Tuple{},NamedTuple{(),Tuple{}}}, ::Function, ::Model) at C:\Users\binha\.julia\packages\JuMP\PbnIJ\src\solvers.jl:168
 [11] solve(::Model) at C:\Users\binha\.julia\packages\JuMP\PbnIJ\src\solvers.jl:150
 [12] top-level scope at none:0
```

### LINKED ISSUE #2368: Can't register erf as :erf
I was trying to register erf as a work around for issue #1803 and ran into the following behavior. If I try to register the function using `:erf ` with the below script then I receive an error.

```
using SpecialFunctions
using JuMP

model = Model()
@variable(model, x)

JuMP.register(model, :erf, 1, x -> erf(x), autodiff = true)
@NLconstraint(model, c1, erf(x) <= 0.0)

d = NLPEvaluator(model)
MOI.initialize(d, Symbol[:Grad])

out = zeros(1)
values = Float64[2.0]
MOI.eval_constraint(d, out, values)
```

Namely, this error:

```
ERROR: LoadError: UndefVarError: erf not defined
Stacktrace:
 [1] eval_univariate at C:\Users\wilhe\.julia\packages\JuMP\e0Uc2\src\_Derivatives\forward.jl:411 [inlined]
 [2] forward_eval(::Array{Float64,1}, ::Array{Float64,1}, ::Array{JuMP._Derivatives.NodeData,1}, ::SparseArrays.SparseMatrixCSC{Bool,Int64}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, ::Array{Float64,1}, 
::Array{Float64,1}, ::Array{Float64,1}, ::JuMP._Derivatives.UserOperatorRegistry) at C:\Users\wilhe\.julia\packages\JuMP\e0Uc2\src\_Derivatives\forward.jl:188
 [3] _forward_eval_all(::NLPEvaluator, ::Array{Float64,1}) at C:\Users\wilhe\.julia\packages\JuMP\e0Uc2\src\nlp.jl:503
 [4] macro expansion at C:\Users\wilhe\.julia\packages\JuMP\e0Uc2\src\nlp.jl:571 [inlined]
 [5] macro expansion at .\timing.jl:233 [inlined]
 [6] eval_constraint(::NLPEvaluator, ::Array{Float64,1}, ::Array{Float64,1}) at C:\Users\wilhe\.julia\packages\JuMP\e0Uc2\src\nlp.jl:569
 [7] top-level scope at C:\Users\wilhe\Dropbox\My PC (DESKTOP-P6322LG)\Desktop\Specials_reg.jl:16
 [8] include_string(::Function, ::Module, ::String, ::String) at .\loading.jl:1088
in expression starting at C:\Users\wilhe\Dropbox\My PC (DESKTOP-P6322LG)\Desktop\Specials_reg.jl:16
```

If I register this function using a different name, like below, everything works out fine.

```
using SpecialFunctions
using JuMP

model = Model()
@variable(model, x)

JuMP.register(model, :random_name, 1, x -> erf(x), autodiff = true)
@NLconstraint(model, c1, random_name(x) <= 0.0)

d = NLPEvaluator(model)
MOI.initialize(d, Symbol[:Grad])

out = zeros(1)
values = Float64[2.0]
MOI.eval_constraint(d, out, values)
```

Version and package info below:

```julia
julia> versioninfo()
Julia Version 1.5.1
Commit 697e782ab8 (2020-08-25 20:08 UTC)
Platform Info:
  OS: Windows (x86_64-w64-mingw32)
  CPU: Intel(R) Core(TM) i9-10900 CPU @ 2.80GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-9.0.1 (ORCJIT, skylake)
Environment:
  JULIA_EDITOR = "C:\Users\wilhe\AppData\Local\atom\app-1.52.0\atom.exe"  -a
  JULIA_NUM_THREADS = 10
```

```
 [c52e3926] Atom v0.12.24
  [6e4b80f9] BenchmarkTools v0.5.0
  [336ed68f] CSV v0.7.7
  [7057c7e9] Cassette v0.3.3
  [e2554f3b] Clp v0.8.1
  [a93c6f00] DataFrames v0.21.7
  [864edb3b] DataStructures v0.17.20
  [163ba53b] DiffResults v1.0.2
  [0c46a032] DifferentialEquations v6.15.0
  [bb8be931] EAGO v0.5.0 `C:\Users\wilhe\Desktop\Package Development\EAGO.jl`
  [587475ba] Flux v0.11.1
  [f6369f11] ForwardDiff v0.10.12
  [4b11ee91] Gaston v1.0.2
  [7073ff75] IJulia v1.22.0
  [d1acc4aa] IntervalArithmetic v0.17.5
  [d2bf35a9] IntervalRootFinding v0.5.4
  [b6b21f68] Ipopt v0.6.3
  [4076af6c] JuMP v0.21.4
  [e5e0dc1b] Juno v0.8.4
  [b964fa9f] LaTeXStrings v1.2.0
  [33e6dc65] MKL v0.2.0 `https://github.com/JuliaComputing/MKL.jl#master`
  [b8f27783] MathOptInterface v0.9.17
  [53c679d3] McCormick v0.9.0 `C:\Users\wilhe\Desktop\Package Development\McCormick.jl`
  [2774e3e8] NLsolve v4.4.1
  [91a5bcdd] Plots v1.6.10
  [d330b81b] PyPlot v2.9.0
  [189a3867] Reexport v0.2.0
  [295af30f] Revise v3.1.4
  [276daf66] SpecialFunctions v0.10.3
  [90137ffa] StaticArrays v0.12.4
  [c3572dad] Sundials v3.9.0
  [d1185830] SymbolicUtils v0.5.1
  [6aa5eb33] TaylorSeries v0.10.8
  [d621b6e3] ValidatedNumerics v0.11.0
```

### PR DESCRIPTION
**Pull request by odow**
Not sure why we didn't consider just adding SpecialFunctions as a dependency earlier.

Closes #1803
Closes #2368

cc @mewilhel

### CODE REVIEW

**Comment by mlubin** [comment]
I think this would be JuMP's first binary dependency. Depends on how much we trust OpenSpecFun_jll and want to answer questions about why it didn't install.

**Comment by odow** [comment]
> how much we trust OpenSpecFun_jll

So on Julia > 1.3, very solid. But it can't use the jll on Julia 1.0 and that is flakey. 

Maybe we should hold-off on this until the LTS version of Julia can use jlls.

**Comment by joaquimg** [comment]
As much as I don't like more dependencies also, JuMP depends on ForwardDiff that depends on SpecialFunctions...
We basically already have that dependency. As pointed by @oxinabox in another chat.

**Review by joaquimg — APPROVED** [review]

**Comment by odow** [comment]
Merging since this fixes a long-standing bug that users frequently encounter, and doesn't add any new dependencies, replacing a transitive dependency for a direct dependency.

**Pull request merged**
