### PR TITLE
[docs] debug failure on v1.11

### PR DESCRIPTION
**Pull request by odow**
Doc build is currently failing on 1.11

### CODE REVIEW

**Comment by odow** [comment]
So it seems like the TSP tutorial has broken. I have no idea why

**Comment by odow** [comment]
My conclusion is that the lazy constraint algorithm in GLPK adds local lazy, so it's just pretty terrible at repeating existing work.

**Comment by blegat** [comment]
Maybe we should use SCIP instead of GLPK but looking at SCIP.jl, it supports `MOI.HeuristicCallback` and `MOI.UserCutCallback` but not `MOI.LazyConstraintCallback`. @matbesancon what is blocking SCIP.jl from adding support to the solver-agnostic lazy callback ?

**Comment by matbesancon** [comment]
Nothing really, there is a constraint handler mechanism that should be a
superset of the lazy constraint, so one could implement a restricted
version for LazyConstraintCallback's sake. And this would keep OSS solvers
for the tests, for people to be able to try things out.

**Pull request merged**
