### PR TITLE
[docs] update should_i_use.md to remove optimal control

### PR DESCRIPTION
**Pull request by odow**
Thoughts? Especially @pulsipher.

With tracing, we have a nice interface now. I don't see any reason to recommend people go elsewhere.

Here's an example of a model that is now much nicer to write https://github.com/jump-dev/JuMP.jl/issues/3622

### CODE REVIEW

**Comment by joaquimg** [comment]
Maybe instead of removing the section completely, keep it, remove the references to other tools and add a link to a tutorial.

**Comment by odow** [comment]
I don't know about keeping the links here. We don't provide links to alternatives for other problem types that JuMP supports. This section is in the "Why shouldn't I use JuMP" bit. And solving an optimal control problem is not a reason not to use JuMP.

I have a TODO to add a MPC tutorial: https://github.com/jump-dev/JuMP.jl/issues/2348#issuecomment-1839210372

People seem to be using (and enjoying) JuMP for optimal control problems:
https://discourse.julialang.org/t/setting-up-free-final-time-in-jump-optimization/107302/3

**Comment by pulsipher** [comment]
Naturally, I like having the reference, but I understand the argument to remove it from the why not to use JuMP section. 

Perhaps an alternative suggestion would be to add some references in the tutorials to relevant JuMP extensions (e.g., InfiniteOpt, SDDP, BilevelJuMP). For instance, it is straightforward to implement an optimal control problem that is discretized with a fixed time step that uses explicit/implicit Euler as demonstrated by existing/future JuMP tutorials; however, using a more complex discretization scheme (e.g., orthogonal collocation over finite elements) is nontrivial to implement. Thus, referring the user to InfiniteOpt to handle these more difficult cases would make sense and highlight that JuMP ecosystem has several useful extensions.

**Comment by odow** [comment]
Added some suggestions https://github.com/jump-dev/JuMP.jl/pull/3625.

I think they are a much better way of suggesting relevant extensions. I doubt many people actually read the "when should I not use JuMP" and then followed the link to an extension.

**Comment by odow** [comment]
Updated to refer to InfiniteOpt and BilevelJuMP in the tutorials.

**Comment by odow** [comment]
See

https://jump.dev/JuMP.jl/previews/PR3623/tutorials/nonlinear/rocket_control/
https://jump.dev/JuMP.jl/previews/PR3623/tutorials/nonlinear/nested_problems/

**Comment by pulsipher** [comment]
I approve of the changes and support this PR. I will also note that InfiniteOpt supports 2-stage stochastic programs like https://jump.dev/JuMP.jl/stable/tutorials/applications/two_stage_stochastic/.

**Pull request merged**
