### PR TITLE
Update to documenter 0.27

### PR DESCRIPTION
**Pull request by odow**
Related to #2631

### CODE REVIEW

**Comment by odow** [comment]
@mortenpi have you seen these errors before? 

> git: symbol lookup error: git: undefined symbol: pcre2_maketables_free_8

I ran into it the other day as well (https://github.com/odow/SDDP.jl/runs/2843898147#step:5:229), but fixed it by building the docs on Julia 1.6 instead of 1.0. (https://github.com/odow/SDDP.jl/pull/425)

**Comment by mortenpi** [comment]
Not really. You're not adding something to LD_LIBRARY_PATH by any chance?

**Comment by odow** [comment]
Ah. It's probably this Ipopt issue: https://github.com/jump-dev/Ipopt.jl/pull/274. Thanks!

**Comment by odow** [comment]
New tag of Ipopt: https://github.com/JuliaRegistries/General/pull/39272

**Pull request merged**
