### PR TITLE
Update constraints.md

### PR DESCRIPTION
**Pull request by ko56**
This point has created a lot of confusion for me.  I hope what I'm saying is correct, I don't exactly know what JuMP is doing.  Also, I don't know markdown, so I wrote in LaTeX.  Please feel free to fix.

### CODE REVIEW

**Comment by mlubin** [comment]
This is useful content to have, but I think it's out of place. It's referring to concepts (i.e., Lagrangian duality and a non-MOI-like formulation of an optimization problem) that haven't been introduced and aren't essential to describing how JuMP works. I'd suggest formulating this as an [example](https://github.com/JuliaOpt/JuMP.jl/tree/master/examples) or [tutorial notebook](https://github.com/JuliaOpt/JuMPTutorials.jl) that gives a concrete example of how to map conic duals from JuMP to Lagrangian duals.

**Comment by ko56** [comment]
I see your point, that this is not relevant to how JuMP works. But the duality section already emphasizes that the MOI definitions may disagree with textbook definitions, and, more specifically, there is a comment on shadow prices, which, in my opinion falls in the same category as the present suggestion.

On Thu, 2019-09-05 at 19:10 -0700, Miles Lubin wrote:

This is useful content to have, but I think it's out of place. It's referring to concepts (i.e., Lagrangian duality and a non-MOI-like formulation of an optimization problem) that haven't been introduced and aren't essential to describing how JuMP works. I'd suggest formulating this as an example<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JuliaOpt_JuMP.jl_tree_master_examples&d=DwMCaQ&c=LFYZ-o9_HUMeMTSQicvjIg&r=vqvTeTq2UMQ06lN1f697Qn2ecAGMFV8KdSndtiiJHbY&m=2OERMeP2NyxoA11yQrW44Xru32AQEphxXpPGABfowfo&s=NOZ3nJ1gIq_UAqneZDEKXo1m2pX_ZACBZNPH4SNLL48&e=> or tutorial notebook<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JuliaOpt_JuMPTutorials.jl&d=DwMCaQ&c=LFYZ-o9_HUMeMTSQicvjIg&r=vqvTeTq2UMQ06lN1f697Qn2ecAGMFV8KdSndtiiJHbY&m=2OERMeP2NyxoA11yQrW44Xru32AQEphxXpPGABfowfo&s=6Ki691eO00PPkpDI-0kXB19wVeNwLdBPA7LxEw3IeXk&e=> that gives a concrete example of how to map conic duals from JuMP to Lagrangian duals.

**Comment by odow** [comment]
I agree with Miles. This might be better suited an example with some discussion on the differences, and then link to it from the documentation.

For an example to follow, take a look at
https://github.com/JuliaOpt/JuMP.jl/blob/master/examples/clnlbeam.jl.

It might be good to formulate the primal, solve and query a dual. Then formulate the Lagrangian (hard-coding the optimal multipliers from the first step) and solve to see that the answer is the same.

**Comment by ko56** [comment]
Hi Oscar,

I don't think this whole topic belongs to an example. Lagrange duality is as fundamental a concept as conic duality, and as a user I would expect the JuMP manual to mention that.

My proposal is to add just two lines to the manual:

Note on Lagrange duality: if you are solving a convex minimization problem subject to linear equalities and convex inequalities, dual() returns the Lagrange multipliers. If you have a concave maximization problem, -dual() does that.

Kostas


On Mon, 2019-09-09 at 11:06 -0700, Oscar Dowson wrote:

I agree with Miles. This might be better suited an example with some discussion on the differences, and then link to it from the documentation.

For an example to follow, take a look at
https://github.com/JuliaOpt/JuMP.jl/blob/master/examples/clnlbeam.jl<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_JuliaOpt_JuMP.jl_blob_master_examples_clnlbeam.jl&d=DwMCaQ&c=LFYZ-o9_HUMeMTSQicvjIg&r=vqvTeTq2UMQ06lN1f697Qn2ecAGMFV8KdSndtiiJHbY&m=10RScbdNXqTcX59_jMJU2bbXhacKQ6Z_08-k-KhLGmE&s=GDS0w4WJkTmvDb1dK6xX3N--kb_f5RfKogrDlgdo0fQ&e=>.

It might be good to formulate the primal, solve and query a dual. Then formulate the Lagrangian (hard-coding the optimal multipliers from the first step) and solve to see that the answer is the same.

**Pull request closed without merging**
