### PR TITLE
Improve error message for non-broadcasted addition and subtraction

### PR DESCRIPTION
**Pull request by odow**
Closes https://github.com/jump-dev/JuMP.jl/issues/3554

Follow-up to #3557 

cc @jd-foster thoughts on this more general error?

### CODE REVIEW

**Comment by jd-foster** [comment]
Looks much more general. I wonder about the related case that also prompted this, #3553, that it might not be obvious that `x * LinearAlgebra.I == 1.0 * x`. I'm not sure this can be covered here, but might be documented somewhere along the lines of the deleted comment "if you are modifying the diagonal entries of the matrix, do `A - x * LinearAlgebra.I(n)`, where `n` is the diagonal length."

**Comment by odow** [comment]
I think in retrospect that supporting `UniformScaling` was the wrong choice. But yeah, I don't have a good answer for where we should document this. Putting it in an error message that probably happens when the user didn't write `I` isn't great either.

**Comment by blegat** [comment]
We can restrict the error message to square matrices. I think it's still nice to include it. It shows why it's ambiguous to add a scalar and a matrix because both would be reasonable interpretations

**Comment by odow** [comment]
How's this

**Review by blegat — APPROVED** [review]
I like it

**Pull request merged**
