### PR TITLE
[docs] update multi.jl tutorial to use an SQLite database

### PR DESCRIPTION
**Pull request by odow**
Preview: https://jump.dev/JuMP.jl/previews/PR3098/tutorials/linear/multi/

Someone mentioned to me that we don't have any examples of using a database, even though that's probably the most common way of working with data in an industrial setting.

I don't think we need to commit it, but here's the script I used to build the database:
```julia
import SQLite
const DBInterface = SQLite.DBInterface
filename = joinpath(@__DIR__, "..", "multi.sqlite")
db = SQLite.DB(filename)
DBInterface.execute(db, """
    CREATE TABLE locations (
        location TEXT,
        type TEXT,
        PRIMARY KEY(location, type)
    );
""")
DBInterface.execute(db, """
INSERT INTO locations (location, type)
VALUES
    ("GARY", "origin"),
    ("CLEV", "origin"),
    ("PITT", "origin"),
    ("FRA", "destination"),
    ("DET", "destination"),
    ("LAN", "destination"),
    ("WIN", "destination"),
    ("STL", "destination"),
    ("FRE", "destination"),
    ("LAF", "destination");
""")
DBInterface.execute(db, """
    CREATE TABLE products (product TEXT PRIMARY KEY);
""")
DBInterface.execute(db, """
INSERT INTO products (product)
VALUES
    ("bands"),("coils"),("plate");
""")
DBInterface.execute(db, """
    CREATE TABLE supply (
        origin TEXT,
        product TEXT,
        supply FLOAT,
        PRIMARY KEY(origin, product)
    );
""")
DBInterface.execute(db, """
INSERT INTO supply (origin,product,supply)
VALUES
    ("GARY","bands",400),
    ("GARY","coils",800),
    ("GARY","plate",200),
    ("CLEV","bands",700),
    ("CLEV","coils",1600),
    ("CLEV","plate",300),
    ("PITT","bands",800),
    ("PITT","coils",1800),
    ("PITT","plate",300);
""")
DBInterface.execute(db, """
CREATE TABLE demand (
    destination TEXT,
    product TEXT,
    demand FLOAT,
    PRIMARY KEY(destination, product)
)
""")
DBInterface.execute(db, """
INSERT INTO demand (destination,product,demand)
VALUES
    ("FRA", "bands", 300),
    ("FRA", "coils", 500),
    ("FRA", "plate", 100),
    ("DET", "bands", 300),
    ("DET", "coils", 750),
    ("DET", "plate", 100),
    ("LAN", "bands", 100),
    ("LAN", "coils", 400),
    ("LAN", "plate", 0),
    ("WIN", "bands", 75),
    ("WIN", "coils", 250),
    ("WIN", "plate", 50),
    ("STL", "bands", 650),
    ("STL", "coils", 950),
    ("STL", "plate", 200),
    ("FRE", "bands", 225),
    ("FRE", "coils", 850),
    ("FRE", "plate", 100),
    ("LAF", "bands", 250),
    ("LAF", "coils", 500),
    ("LAF", "plate", 250);
""")
DBInterface.execute(db, """
CREATE TABLE cost (
    origin TEXT,
    destination TEXT,
    product TEXT,
    cost FLOAT,
    PRIMARY KEY(origin, destination, product)
)
""")
DBInterface.execute(db, """
INSERT INTO cost (origin,destination,product,cost)
VALUES
    ("GARY", "FRA", "bands", 30),
    ("GARY", "FRA", "coils", 39),
    ("GARY", "FRA", "plate", 41),
    ("GARY", "DET", "bands", 10),
    ("GARY", "DET", "coils", 14),
    ("GARY", "DET", "plate", 15),
    ("GARY", "LAN", "bands", 8),
    ("GARY", "LAN", "coils", 11),
    ("GARY", "LAN", "plate", 12),
    ("GARY", "WIN", "bands", 10),
    ("GARY", "WIN", "coils", 14),
    ("GARY", "WIN", "plate", 16),
    ("GARY", "STL", "bands", 11),
    ("GARY", "STL", "coils", 16),
    ("GARY", "STL", "plate", 17),
    ("GARY", "FRE", "bands", 71),
    ("GARY", "FRE", "coils", 82),
    ("GARY", "FRE", "plate", 86),
    ("GARY", "LAF", "bands", 6),
    ("GARY", "LAF", "coils", 8),
    ("GARY", "LAF", "plate", 8),
    ("CLEV", "FRA", "bands", 22),
    ("CLEV", "FRA", "coils", 27),
    ("CLEV", "FRA", "plate", 29),
    ("CLEV", "DET", "bands", 7),
    ("CLEV", "DET", "coils", 9),
    ("CLEV", "DET", "plate", 9),
    ("CLEV", "LAN", "bands", 10),
    ("CLEV", "LAN", "coils", 12),
    ("CLEV", "LAN", "plate", 13),
    ("CLEV", "WIN", "bands", 7),
    ("CLEV", "WIN", "coils", 9),
    ("CLEV", "WIN", "plate", 9),
    ("CLEV", "STL", "bands", 21),
    ("CLEV", "STL", "coils", 26),
    ("CLEV", "STL", "plate", 28),
    ("CLEV", "FRE", "bands", 82),
    ("CLEV", "FRE", "coils", 95),
    ("CLEV", "FRE", "plate", 99),
    ("CLEV", "LAF", "bands", 13),
    ("CLEV", "LAF", "coils", 17),
    ("CLEV", "LAF", "plate", 18),
    ("PITT", "FRA", "bands", 19),
    ("PITT", "FRA", "coils", 24),
    ("PITT", "FRA", "plate", 26),
    ("PITT", "DET", "bands", 11),
    ("PITT", "DET", "coils", 14),
    ("PITT", "DET", "plate", 14),
    ("PITT", "LAN", "bands", 12),
    ("PITT", "LAN", "coils", 17),
    ("PITT", "LAN", "plate", 17),
    ("PITT", "WIN", "bands", 10),
    ("PITT", "WIN", "coils", 13),
    ("PITT", "WIN", "plate", 13),
    ("PITT", "STL", "bands", 25),
    ("PITT", "STL", "coils", 28),
    ("PITT", "STL", "plate", 31),
    ("PITT", "FRE", "bands", 83),
    ("PITT", "FRE", "coils", 99),
    ("PITT", "FRE", "plate", 104),
    ("PITT", "LAF", "bands", 15),
    ("PITT", "LAF", "coils", 20),
    ("PITT", "LAF", "plate", 20);
""")
```

### CODE REVIEW

**Comment by joaquimg** [comment]
What is the downside of committing the database generator?

**Comment by odow** [comment]
> What is the downside of committing the database generator?

It's too lengthy/does't really fit in the tutorials/documentatio. I guess we could and run it in the `make.jl`, but then it means that people can't download the `multi.sqlite` file directly.

**Comment by joaquimg** [comment]
I think we should at least leave the file that generated the SQL binary committed so that one can easily modify the file if needed, or debug some issues or even extend/improve the tutorial later. I don't like the idea of keeping an opaque binary living there all alone.

**Comment by joaquimg** [comment]
the binary is 44kb while the generator is not even 5kb, so it is not lengthy it is actually negligible to keep the generator.

**Comment by odow** [comment]
> I don't like the idea of keeping an opaque binary living there all alone.

I mean, it's an SQLite file. So not really some opaque binary. 

I guess by lengthy, I meant that we don't want it into the documentation, and we probably don't want to rebuild the database every time? So checking it in without running it might lead to bit-rot, and doesn't serve any better purpose than the comment in this PR.

**Pull request merged**
