### PR TITLE
[docs] add CasADi to Should I use JuMP?

### LINKED ISSUE #2871: [docs] Mention CasADi as an alternative to JuMP
Mention CasADi[.jl] as an alternative in https://jump.dev/JuMP.jl/dev/should_i_use/.

Context: https://discourse.julialang.org/t/jump-hessian-sparcity-issues-registered-functions-hessians-atan2-issue/76342/5

### PR DESCRIPTION
**Pull request by odow**
Closes #2871

### CODE REVIEW

**Comment by mlubin** [comment]
@ChrisRackauckas, are there any pointers you'd like us to add here?

**Comment by pulsipher** [comment]
It might be worth mentioning InfiniteOpt.jl as an alternative for optimal control. Its nonlinear interface is more flexible than JuMP's and it can model optimal control problems in continuous time. Plus, some more optimal control specific features are currently under development and should be released in a month or two. I am also working on an interface to ModelingToolkit.jl to facilitate model transfer, automatic initialization/simulation, and model simplification (e.g., order reduction).

**Comment by pulsipher** [comment]
Also, albeit with a more limited NLP interface, Pyomo.dae is probably worth mentioning.

**Comment by odow** [comment]
I added InfiniteOpt and pyomo.DAE.

**Comment by odow** [comment]
Merging for now. If @ChrisRackauckas has other suggestions, we can make a follow-up PR.

**Pull request merged**
